package com.jagex.runescape;

public class StringUtilities {
    public static JagexString startupSongName = JagexString.getRs2PreparedString("barbarianism");
    // English

    // German

    public static JagexString aJagexString_1458 = JagexString.getRs2PreparedString("blinken3:");
    public static JagexString aJagexString_1463 = JagexString.getRs2PreparedString("Existing User");
    public static JagexString aJagexString_69 = JagexString.getRs2PreparedString("Abbrechen");
    public static JagexString aJagexString_72 = JagexString.getRs2PreparedString("Sie befinden sich in einem Mitglieder)2Gebiet(Q");
    public static JagexString aJagexString_79 = JagexString.getRs2PreparedString("60 Sekunden noch einmal)3)3)3");
    public static JagexString aJagexString_295 = JagexString.getRs2PreparedString("flash2:");
    public static JagexString aJagexString_297 = JagexString.getRs2PreparedString("flash2:");
    public static JagexString aJagexString_300 = JagexString.getRs2PreparedString("leuchten2:");
    public static JagexString aJagexString_301 = JagexString.getRs2PreparedString(")4l");
    public static JagexString aJagexString_302 = JagexString.getRs2PreparedString("Der Server wird gerade aktualisiert)3");
    public static JagexString aJagexString_303 = JagexString.getRs2PreparedString("<col=00ffff>");
    public static JagexString aJagexString_308 = JagexString.getRs2PreparedString("http:)4)4");
    public static JagexString aJagexString_309 = JagexString.getRs2PreparedString("va");
    public static JagexString aJagexString_310 = JagexString.getRs2PreparedString("Ausw-=hlen");
    public static JagexString aJagexString_311 = JagexString.getRs2PreparedString("Connecting to server)3)3)3");
    public static JagexString aJagexString_312 = JagexString.getRs2PreparedString(" steht bereits auf Ihrer Ignorieren)2Liste(Q");
    public static JagexString aJagexString_315 = JagexString.getRs2PreparedString("blinken2:");
    public static JagexString aJagexString_316 = JagexString.getRs2PreparedString("<br>");
    public static JagexString aJagexString_317 = JagexString.getRs2PreparedString("(U2");
    public static JagexString aJagexString_322 = JagexString.getRs2PreparedString(")1j");
    public static JagexString aJagexString_323 = JagexString.getRs2PreparedString("Enter your username (V password)3");
    public static JagexString aJagexString_324 = JagexString.getRs2PreparedString("sl_stars");
    public static JagexString aJagexString_328 = JagexString.getRs2PreparedString("Ihre Freunde)2Liste ist voll(Q Mitglieder k-Onnen 200 Freunde hinzuf-Ugen)1 freie Spieler nur 100)3");
    public static JagexString aJagexString_346 = JagexString.getRs2PreparedString("Malformed login packet)3");
    public static JagexString aJagexString_361 = JagexString.getRs2PreparedString("sl_arrows");
    public static JagexString aJagexString_363 = JagexString.getRs2PreparedString("Service unavailable)3");
    public static JagexString aJagexString_370 = JagexString.getRs2PreparedString("Error loading your profile)3");
    public static JagexString aJagexString_373 = JagexString.getRs2PreparedString("Bitte entfernen Sie ");
    public static JagexString aJagexString_386 = JagexString.getRs2PreparedString("welle2:");
    public static JagexString aJagexString_2469 = JagexString.getRs2PreparedString("me");
    public static JagexString aJagexString_2474 = JagexString.getRs2PreparedString("flash1:");
    public static JagexString aJagexString_2475 = JagexString.getRs2PreparedString("Update)2Liste geladen)3");
    public static JagexString aJagexString_2477 = JagexString.getRs2PreparedString("Bitte laden Sie die Seite neu)3");
    public static JagexString aJagexString_2479 = JagexString.getRs2PreparedString("flash1:");
    public static JagexString aJagexString_390 = JagexString.getRs2PreparedString("Musik)2Engine vorbereitet)3");
    public static JagexString aJagexString_393 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_396 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_397 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_398 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_400 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_402 = JagexString.getRs2PreparedString("(Udns");
    public static JagexString aJagexString_403 = JagexString.getRs2PreparedString("white:");
    public static JagexString aJagexString_407 = JagexString.getRs2PreparedString("white:");
    public static JagexString aJagexString_411 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_413 = JagexString.getRs2PreparedString("Sie k-Onnen sich selbst nicht auf Ihre Freunde)2Liste setzen(Q");
    public static JagexString aJagexString_432 = JagexString.getRs2PreparedString("Loading textures )2 ");
    public static JagexString aJagexString_434 = JagexString.getRs2PreparedString("Walk here");
    public static JagexString aJagexString_445 = JagexString.getRs2PreparedString("<col=00ff80>");
    public static JagexString aJagexString_451 = JagexString.getRs2PreparedString("rect_debug=");
    public static JagexString aJagexString_2936 = JagexString.getRs2PreparedString("Cabbage");
    public static JagexString aJagexString_2101 = JagexString.getRs2PreparedString(":");
    public static JagexString aJagexString_2115 = JagexString.getRs2PreparedString(": ");
    public static JagexString aJagexString_368 = JagexString.getRs2PreparedString("l");
    public static JagexString aJagexString_464 = JagexString.getRs2PreparedString("Wir vermuten)1 dass Ihr Konto gestohlen wurde");
    public static JagexString aJagexString_470 = JagexString.getRs2PreparedString("Try again in 60 secs)3)3)3");
    public static JagexString aJagexString_472 = JagexString.getRs2PreparedString("k");
    public static JagexString aJagexString_474 = (JagexString.getRs2PreparedString("Benutzen Sie die (WPasswort -=ndern(W Option"));
    public static JagexString aJagexString_478 = JagexString.getRs2PreparedString(":tradereq:");
    public static JagexString aJagexString_484 = JagexString.getRs2PreparedString("<)4col> x");
    public static JagexString aJagexString_495 = (JagexString.getRs2PreparedString("Verbindung konnte nicht hergestellt werden)3"));
    public static JagexString aJagexString_517 = JagexString.getRs2PreparedString("<col=ffffff> )4 ");
    public static JagexString aJagexString_2514 = JagexString.getRs2PreparedString("Loaded wordpack");
    public static JagexString aJagexString_2515 = JagexString.getRs2PreparedString("Bitte geben Sie Ihr Passwort ein)3");
    public static JagexString aJagexString_2518 = JagexString.getRs2PreparedString(":chalreq:");
    public static JagexString aJagexString_2528 = JagexString.getRs2PreparedString("mapscene");
    public static JagexString aJagexString_81 = JagexString.getRs2PreparedString("Clientscript error in: ");
    public static JagexString aJagexString_85 = JagexString.getRs2PreparedString("_");
    public static JagexString aJagexString_92 = JagexString.getRs2PreparedString("titlebox");
    public static JagexString aJagexString_93 = JagexString.getRs2PreparedString("No response from server)3");
    public static JagexString aJagexString_558 = JagexString.getRs2PreparedString("0(U");
    public static JagexString aJagexString_560 = JagexString.getRs2PreparedString("AUS");
    public static JagexString aJagexString_563 = JagexString.getRs2PreparedString("Choose Option");
    public static JagexString drop = JagexString.getRs2PreparedString("Drop");
    public static JagexString aJagexString_565 = JagexString.getRs2PreparedString(":assistreq:");
    public static JagexString aJagexString_551 = JagexString.getRs2PreparedString("Hidden)2");
    public static JagexString aJagexString_581 = JagexString.getRs2PreparedString(" is already on your friend list");
    public static JagexString aJagexString_586 = JagexString.getRs2PreparedString("Select");
    public static JagexString aJagexString_594 = JagexString.getRs2PreparedString("Bitte versuchen Sie)1");
    public static JagexString aJagexString_595 = JagexString.getRs2PreparedString("Angreifen");
    public static JagexString aJagexString_596 = JagexString.getRs2PreparedString("Spieler)3 Bitte w-=hlen Sie eine andere Welt)3");
    public static JagexString aJagexString_622 = JagexString.getRs2PreparedString("::clientdrop");
    public static JagexString aJagexString_623 = JagexString.getRs2PreparedString("Bitte versuchen Sie es in ");
    public static JagexString aJagexString_624 = JagexString.getRs2PreparedString("Your friend list is full)3 Max of 100 for free users)1 and 200 for members");
    public static JagexString aJagexString_629 = JagexString.getRs2PreparedString("Members only world");
    public static JagexString hidden = JagexString.getRs2PreparedString("Hidden");
    public static JagexString aJagexString_651 = JagexString.getRs2PreparedString("Invalid loginserver requested)3");
    public static JagexString aJagexString_652 = JagexString.getRs2PreparedString("(Y");
    public static JagexString aJagexString_653 = JagexString.getRs2PreparedString(" zuerst von Ihrer Freunde)2Liste(Q");
    public static JagexString aJagexString_659 = JagexString.getRs2PreparedString("::fpsoff");
    public static JagexString aJagexString_662 = JagexString.getRs2PreparedString("Loading title screen )2 ");
    public static JagexString aJagexString_665 = JagexString.getRs2PreparedString("Examine");
    public static JagexString aJagexString_675 = JagexString.getRs2PreparedString("Create a free account");
    public static JagexString aJagexString_678 = JagexString.getRs2PreparedString("sl_back");
    public static JagexString aJagexString_679 = JagexString.getRs2PreparedString("Bad session id)3");
    public static JagexString aJagexString_681 = JagexString.getRs2PreparedString("M");
    public static JagexString aJagexString_684 = JagexString.getRs2PreparedString("(U(Y");
    public static JagexString aJagexString_685 = JagexString.getRs2PreparedString("Diese Welt ist voll)3");
    public static JagexString aJagexString_688 = JagexString.getRs2PreparedString("Spiel)2Engine wird gestartet)3)3)3");
    public static JagexString aJagexString_692 = JagexString.getRs2PreparedString("Bad session id)3");
    public static JagexString aJagexString_695 = JagexString.getRs2PreparedString("blaugr-Un:");
    public static JagexString aJagexString_700 = JagexString.getRs2PreparedString("Lade Benutzeroberfl-=che )2 ");
    public static JagexString aJagexString_701 = JagexString.getRs2PreparedString("Passwort: ");
    public static JagexString aJagexString_1753 = JagexString.getRs2PreparedString("Bitte versuchen Sie es erneut)3");
    public static JagexString aJagexString_1759 = JagexString.getRs2PreparedString(")3runescape)3com");
    public static JagexString aJagexString_1762 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1764 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1766 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1768 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1769 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1771 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1767 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_728 = JagexString.getRs2PreparedString("You are standing in a members)2only area)3");
    public static JagexString aJagexString_735 = JagexString.getRs2PreparedString("null");
    public static JagexString aJagexString_741 = JagexString.getRs2PreparedString("Zu viele Anmelde)2Versuche von Ihrer Adresse");
    public static JagexString aJagexString_753 = JagexString.getRs2PreparedString("Sorry invited players only)3");
    public static JagexString aJagexString_762 = JagexString.getRs2PreparedString("hitmarks");
    public static JagexString aJagexString_765 = JagexString.getRs2PreparedString("Please subscribe)1 or use a different world)3");
    public static JagexString aJagexString_769 = JagexString.getRs2PreparedString("Standort");
    public static JagexString aJagexString_772 = JagexString.getRs2PreparedString("scrollbar");
    public static JagexString aJagexString_788 = JagexString.getRs2PreparedString("We suspect someone knows your password)3");
    public static JagexString aJagexString_791 = JagexString.getRs2PreparedString(" )2>");
    public static JagexString aJagexString_797 = JagexString.getRs2PreparedString("This computers address has been blocked");
    public static JagexString aJagexString_804 = JagexString.getRs2PreparedString("null");
    public static JagexString aJagexString_835 = JagexString.getRs2PreparedString("oder benutzen Sie eine andere Welt)3");
    public static JagexString aJagexString_836 = JagexString.getRs2PreparedString("cyan:");
    public static JagexString aJagexString_838 = JagexString.getRs2PreparedString(" <col=ffffff>");
    public static JagexString aJagexString_839 = JagexString.getRs2PreparedString("cyan:");
    public static JagexString aJagexString_840 = JagexString.getRs2PreparedString("huffman");
    public static JagexString aJagexString_842 = JagexString.getRs2PreparedString(" )2> <col=ff9040>");
    public static JagexString aJagexString_843 = JagexString.getRs2PreparedString("Diese Betatest)2Welt ist nur f-Ur eingeladene");
    public static JagexString aJagexString_846 = JagexString.getRs2PreparedString(")2");
    public static JagexString aJagexString_850 = JagexString.getRs2PreparedString("Benutzen Sie bitte eine andere Welt)3");
    public static JagexString aJagexString_857 = JagexString.getRs2PreparedString(")1p");
    public static JagexString aJagexString_864 = JagexString.getRs2PreparedString("Loaded textures");
    public static JagexString aJagexString_867 = JagexString.getRs2PreparedString("as it was used to break our rules)3");
    public static JagexString aJagexString_889 = JagexString.getRs2PreparedString("Bitte wenden Sie sich an den Kundendienst)3");
    public static JagexString aJagexString_905 = JagexString.getRs2PreparedString("Login server offline)3");
    public static JagexString aJagexString_918 = JagexString.getRs2PreparedString("Mem:");
    public static JagexString aJagexString_921 = JagexString.getRs2PreparedString("Schlie-8en");
    public static JagexString aJagexString_922 = JagexString.getRs2PreparedString(" <col=ffff00>");
    public static JagexString aJagexString_924 = JagexString.getRs2PreparedString("Lade Sprites )2 ");
    public static JagexString aJagexString_925 = JagexString.getRs2PreparedString("<col=ff7000>");
    public static JagexString aJagexString_278 = JagexString.getRs2PreparedString("<col=40ff00>");
    public static JagexString aJagexString_3234 = JagexString.getRs2PreparedString("Checking for updates )2 ");
    public static JagexString aJagexString_3238 = JagexString.getRs2PreparedString("Ihr Spielkonto wird bereits benutzt)3");
    public static JagexString aJagexString_3243 = JagexString.getRs2PreparedString("lila:");
    public static JagexString aJagexString_3284 = JagexString.getRs2PreparedString("mapfunction");
    public static JagexString aJagexString_3285 = JagexString.getRs2PreparedString(")4slr)3ws?order=LPWM");
    public static JagexString aJagexString_3294 = JagexString.getRs2PreparedString("m");
    public static JagexString aJagexString_928 = JagexString.getRs2PreparedString("Weiter");
    public static JagexString aJagexString_930 = JagexString.getRs2PreparedString("au");
    public static JagexString aJagexString_942 = JagexString.getRs2PreparedString(" ");
    public static JagexString aJagexString_944 = JagexString.getRs2PreparedString("gleiten:");
    public static JagexString aJagexString_947 = JagexString.getRs2PreparedString("Jul");
    public static JagexString aJagexString_948 = JagexString.getRs2PreparedString("Mar");
    public static JagexString aJagexString_949 = JagexString.getRs2PreparedString("Jan");
    public static JagexString aJagexString_950 = JagexString.getRs2PreparedString("Nov");
    public static JagexString aJagexString_952 = JagexString.getRs2PreparedString("May");
    public static JagexString aJagexString_956 = JagexString.getRs2PreparedString("Sep");
    public static JagexString aJagexString_961 = JagexString.getRs2PreparedString("Ung-Ultiger Benutzername");
    public static JagexString aJagexString_962 = JagexString.getRs2PreparedString(":duelreq:");
    public static JagexString aJagexString_963 = JagexString.getRs2PreparedString("Apr");
    public static JagexString aJagexString_965 = JagexString.getRs2PreparedString("Dec");
    public static JagexString aJagexString_966 = JagexString.getRs2PreparedString("Jun");
    public static JagexString aJagexString_967 = JagexString.getRs2PreparedString("Aug");
    public static JagexString aJagexString_970 = JagexString.getRs2PreparedString("Feb");
    public static JagexString aJagexString_972 = JagexString.getRs2PreparedString("Oct");
    public static JagexString[] aJagexStringArray954 = new JagexString[]{aJagexString_949, aJagexString_970,
            aJagexString_948, aJagexString_963, aJagexString_952, aJagexString_966,
            aJagexString_947, aJagexString_967, aJagexString_956, aJagexString_972,
            aJagexString_950, aJagexString_965};
    public static JagexString aJagexString_985 = JagexString.getRs2PreparedString("Please contact customer support)3");
    public static JagexString aJagexString_986 = JagexString.getRs2PreparedString("<img=0>");
    public static JagexString aJagexString_988 = JagexString.getRs2PreparedString("oberen Rand der Webseite ausw-=hlen)3");
    public static JagexString aJagexString_1001 = JagexString.getRs2PreparedString("Benutzeroberfl-=che geladen)3");
    public static JagexString aJagexString_1004 = JagexString.getRs2PreparedString("Bitte warten Sie )2 es wird versucht)1 die Verbindung wiederherzustellen)3");
    public static JagexString aJagexString_1868 = JagexString.getRs2PreparedString(" )2> ");
    public static JagexString aJagexString_1869 = JagexString.getRs2PreparedString("go back to the main RuneScape webpage");
    public static JagexString aJagexString_1856 = JagexString.getRs2PreparedString("<col=ff3000>");
    public static JagexString aJagexString_2046 = JagexString.getRs2PreparedString(" from your ignore list first");
    public static JagexString aJagexString_2047 = JagexString.getRs2PreparedString(": ");
    public static JagexString aJagexString_2048 = JagexString.getRs2PreparedString("leuchten1:");
    public static JagexString aJagexString_2049 = JagexString.getRs2PreparedString("The server is being updated)3");
    public static JagexString aJagexString_2678 = JagexString.getRs2PreparedString("-5berpr-Ufen Sie Ihr Mitteilungsfach)3");
    public static JagexString aJagexString_2679 = (JagexString.getRs2PreparedString("Die Adresse dieses Computers wurde gesperrt)1"));
    public static JagexString aJagexString_2692 = JagexString.getRs2PreparedString("Gegenstand f-Ur Mitglieder");
    public static JagexString aJagexString_2693 = JagexString.getRs2PreparedString(" <col=00ff80>");
    public static JagexString aJagexString_2694 = JagexString.getRs2PreparedString("Fehler bei der Verbindung zum Server)3");
    public static JagexString[] aJagexStringArray2671 = new JagexString[1000];
    public static JagexString[] aJagexStringArray2673 = new JagexString[1000];
    public static JagexString aJagexString_2129 = JagexString.getRs2PreparedString("scrollen:");
    public static JagexString aJagexString_2271 = JagexString.getRs2PreparedString(" )2> <col=ffff00>");
    public static JagexString aJagexString_2274 = JagexString.getRs2PreparedString("sind fehlgeschlagen)3 Bitte warten Sie 5 Minuten)1");
    public static JagexString aJagexString_2278 = JagexString.getRs2PreparedString("Lade)3)3)3");
    public static JagexString aJagexString_2285 = JagexString.getRs2PreparedString("<br>(X100(U(Y");
    public static JagexString aJagexString_2287 = JagexString.getRs2PreparedString("Bitte warten Sie)3)3)3");
    public static JagexString aJagexString_2288 = JagexString.getRs2PreparedString("null");
    public static JagexString aJagexString_2291 = JagexString.getRs2PreparedString("Verbindung abgebrochen)3");
    public static JagexString aJagexString_2292 = JagexString.getRs2PreparedString("oder ung-Ultiges Passwort)3");
    public static JagexString aJagexString_2294 = JagexString.getRs2PreparedString("Fertigkeit)2");
    public static JagexString aJagexString_2322 = JagexString.getRs2PreparedString("Mitglieder)2Welt");
    public static JagexString aJagexString_2325 = JagexString.getRs2PreparedString("button near the top of that page)3");
    public static JagexString aJagexString_2328 = JagexString.getRs2PreparedString("Lade Wordpack )2 ");
    public static JagexString aJagexString_2334 = JagexString.getRs2PreparedString("Regeln versto-8en hat)3");
    public static JagexString aJagexString_2352 = JagexString.getRs2PreparedString("T");
    public static JagexString aJagexString_2356 = JagexString.getRs2PreparedString("Keine Antwort vom Anmelde)2Server)3");
    public static JagexString aJagexString_2731 = JagexString.getRs2PreparedString("This world is running a closed Beta)3");
    public static JagexString aJagexString_2733 = JagexString.getRs2PreparedString(" x ");
    public static JagexString aJagexString_2738 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_3067 = JagexString.getRs2PreparedString(" is already on your ignore list");
    public static JagexString aJagexString_3069 = JagexString.getRs2PreparedString("Welcome to RuneScape");
    public static JagexString aJagexString_3071 = JagexString.getRs2PreparedString("event_opbase");
    public static JagexString aJagexString_3072 = JagexString.getRs2PreparedString("<)4col>");
    public static JagexString aJagexString_3056 = JagexString.getRs2PreparedString("mapedge");
    public static JagexString aJagexString_3074 = JagexString.getRs2PreparedString("Loading)3)3)3");
    public static JagexString aJagexString_3078 = JagexString.getRs2PreparedString("Bitte starten Sie eine Mitgliedschaft");
    public static JagexString aJagexString_3081 = JagexString.getRs2PreparedString("<br>(X");
    public static JagexString aJagexString_3089 = JagexString.getRs2PreparedString("Unexpected loginserver response)3");
    public static JagexString aJagexString_3090 = JagexString.getRs2PreparedString("titlebutton");
    public static JagexString aJagexString_3094 = JagexString.getRs2PreparedString("glow1:");
    public static JagexString aJagexString_3095 = JagexString.getRs2PreparedString("glow1:");
    public static JagexString aJagexString_3096 = JagexString.getRs2PreparedString("Members object");
    public static JagexString aJagexString_3547 = JagexString.getRs2PreparedString(")4col");
    public static JagexString aJagexString_3548 = JagexString.getRs2PreparedString("str");
    public static JagexString aJagexString_3550 = JagexString.getRs2PreparedString(")4str");
    public static JagexString aJagexString_3551 = JagexString.getRs2PreparedString(")4shad");
    public static JagexString aJagexString_3552 = JagexString.getRs2PreparedString("br");
    public static JagexString aJagexString_3554 = JagexString.getRs2PreparedString("shad");
    public static JagexString aJagexString_3557 = JagexString.getRs2PreparedString("u=");
    public static JagexString aJagexString_3560 = JagexString.getRs2PreparedString("lt");
    public static JagexString aJagexString_3563 = JagexString.getRs2PreparedString("shad=");
    public static JagexString aJagexString_3564 = JagexString.getRs2PreparedString(")4u");
    public static JagexString aJagexString_3565 = JagexString.getRs2PreparedString("col=");
    public static JagexString aJagexString_3568 = JagexString.getRs2PreparedString("gt");
    public static JagexString aJagexString_3569 = JagexString.getRs2PreparedString("str=");
    public static JagexString aJagexString_3574 = JagexString.getRs2PreparedString("img=");
    public static JagexString aJagexString_3576 = JagexString.getRs2PreparedString("u");
    public static JagexString[] aJagexStringArray3578 = new JagexString[100];
    public static JagexString aJagexString_3108 = JagexString.getRs2PreparedString("<col=c0ff00>");
    public static JagexString aJagexString_3120 = JagexString.getRs2PreparedString("Fallen lassen");
    public static JagexString aJagexString_3135 = JagexString.getRs2PreparedString("Keine Antwort vom Server)3");
    public static JagexString aJagexString_3136 = JagexString.getRs2PreparedString("Unable to connect)3");
    public static JagexString aJagexString_3137 = JagexString.getRs2PreparedString("Wordpack geladen)3");
    public static JagexString aJagexString_3145 = JagexString.getRs2PreparedString("Einloggen");
    public static JagexString aJagexString_3147 = JagexString.getRs2PreparedString("Unable to connect)3");
    public static JagexString aJagexString_3162 = (JagexString.getRs2PreparedString("Wir vermuten)1 dass jemand Ihr Passwort kennt)3"));
    public static JagexString aJagexString_3165  = JagexString.getRs2PreparedString("Invalid username or password)3");
    public static JagexString aJagexString_3180 = JagexString.getRs2PreparedString("Verbindung mit Update)2Server)3)3)3");
    public static JagexString aJagexString_3181 = JagexString.getRs2PreparedString("<col=ffffff>");
    public static JagexString aJagexString_3197 = JagexString.getRs2PreparedString("(U5");
    public static JagexString aJagexString_3210 = JagexString.getRs2PreparedString("<img=1>");
    public static JagexString aJagexString_3214 = JagexString.getRs2PreparedString("runes");
    public static JagexString aJagexString_2794 = JagexString.getRs2PreparedString("wishes to duel with you)3");
    public static JagexString aJagexString_2795 = JagexString.getRs2PreparedString("Titelbild geladen)3");
    public static JagexString aJagexString_2803 = JagexString.getRs2PreparedString("<col=80ff00>");
    public static JagexString aJagexString_2813 = JagexString.getRs2PreparedString("Unable to find ");
    public static JagexString aJagexString_2830 = JagexString.getRs2PreparedString("Registrierter Benutzer");
    public static JagexString aJagexString_2840 = (JagexString.getRs2PreparedString("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789(Q(R+R(T(U^(V(Z(X(Y)2_=)0[*U]*W;:(W@(S*X)1<)3>)4?*6*V "));
    public static JagexString aJagexString_2841 = JagexString.getRs2PreparedString("Loaded title screen");
    public static JagexString aJagexString_2852 = JagexString.getRs2PreparedString("scroll:");
    public static JagexString aJagexString_2853 = JagexString.getRs2PreparedString("purple:");
    public static JagexString aJagexString_2854 = JagexString.getRs2PreparedString("purple:");
    public static JagexString aJagexString_2855 = JagexString.getRs2PreparedString("jolt");
    public static JagexString aJagexString_2860 = JagexString.getRs2PreparedString("scroll:");
    public static JagexString aJagexString_2864 = JagexString.getRs2PreparedString(")3");
    public static JagexString aJagexString_2866 = JagexString.getRs2PreparedString("weiss:");
    public static JagexString aJagexString_2868 = JagexString.getRs2PreparedString("headicons_prayer");
    public static JagexString aJagexString_2873 = JagexString.getRs2PreparedString("gr-Un:");
    public static JagexString aJagexString_2884 = JagexString.getRs2PreparedString("Loading fonts )2 ");
    public static JagexString aJagexString_2885 = (JagexString.getRs2PreparedString("Ung-Ultige Verbindung mit einem Anmelde)2Server)3"));
    public static JagexString aJagexString_2886 = JagexString.getRs2PreparedString("::fpson");
    public static JagexString aJagexString_2890 = JagexString.getRs2PreparedString("Anmelde)2Limit -Uberschritten)3");
    public static JagexString aJagexString_2891 = JagexString.getRs2PreparedString(" )2> <col=00ffff>");
    public static JagexString aJagexString_2894 = JagexString.getRs2PreparedString("Ung-Ultige Session)2ID)3");
    public static JagexString[] aJagexStringArray2893 = new JagexString[200];
    public static JagexString aJagexString_2896 = JagexString.getRs2PreparedString("Lade Titelbild )2 ");
    public static JagexString aJagexString_2897 = JagexString.getRs2PreparedString("You can(Wt add yourself to your own ignore list");
    public static JagexString aJagexString_2899  = JagexString.getRs2PreparedString("Click to switch");
    public static JagexString aJagexString_2904 = JagexString.getRs2PreparedString("p11_full");
    public static JagexString aJagexString_2905 = (JagexString.getRs2PreparedString("Fehler beim Laden Ihres Spielcharakters)3"));
    public static JagexString aJagexString_2919 = JagexString.getRs2PreparedString("Loaded input handler");
    public static JagexString aJagexString_2931 = JagexString.getRs2PreparedString("Please reload this page)3");
    public static JagexString aJagexString_3332 = JagexString.getRs2PreparedString("auf der Hautpseite)3");
    public static JagexString aJagexString_3334 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_3337 = JagexString.getRs2PreparedString("title_mute");
    public static JagexString aJagexString_3343  = JagexString.getRs2PreparedString(" has logged in)3");
    public static JagexString aJagexString_3355 = (JagexString.getRs2PreparedString("RuneScape wird geladen )2 bitte warten)3)3)3"));
    public static JagexString aJagexString_2305 = JagexString.getRs2PreparedString("Attack");
    public static JagexString aJagexString_2312 = JagexString.getRs2PreparedString("Account locked as we suspect it has been stolen)3");
    public static JagexString aJagexString_2317  = JagexString.getRs2PreparedString("You have only just left another world)3");
}
