package com.jagex.runescape;

public class StringUtilities {
    // English

    // German

    public static JagexString aJagexString_1458 = JagexString.getRs2PreparedString("blinken3:");
    public static JagexString aJagexString_1463 = JagexString.getRs2PreparedString("Existing User");
    public static JagexString aJagexString_69 = JagexString.getRs2PreparedString("Abbrechen");
    public static JagexString aJagexString_72 = JagexString.getRs2PreparedString("Sie befinden sich in einem Mitglieder)2Gebiet(Q");
    public static JagexString aJagexString_79 = JagexString.getRs2PreparedString("60 Sekunden noch einmal)3)3)3");
    public static JagexString aJagexString_295 = JagexString.getRs2PreparedString("flash2:");
    public static JagexString aJagexString_297 = JagexString.getRs2PreparedString("flash2:");
    public static JagexString aJagexString_300 = JagexString.getRs2PreparedString("leuchten2:");
    public static JagexString aJagexString_301 = JagexString.getRs2PreparedString(")4l");
    public static JagexString aJagexString_302 = JagexString.getRs2PreparedString("Der Server wird gerade aktualisiert)3");
    public static JagexString aJagexString_303 = JagexString.getRs2PreparedString("<col=00ffff>");
    public static JagexString aJagexString_308 = JagexString.getRs2PreparedString("http:)4)4");
    public static JagexString aJagexString_309 = JagexString.getRs2PreparedString("va");
    public static JagexString aJagexString_310 = JagexString.getRs2PreparedString("Ausw-=hlen");
    public static JagexString aJagexString_311 = JagexString.getRs2PreparedString("Connecting to server)3)3)3");
    public static JagexString aJagexString_312 = JagexString.getRs2PreparedString(" steht bereits auf Ihrer Ignorieren)2Liste(Q");
    public static JagexString aJagexString_315 = JagexString.getRs2PreparedString("blinken2:");
    public static JagexString aJagexString_316 = JagexString.getRs2PreparedString("<br>");
    public static JagexString aJagexString_317 = JagexString.getRs2PreparedString("(U2");
    public static JagexString aJagexString_322 = JagexString.getRs2PreparedString(")1j");
    public static JagexString aJagexString_323 = JagexString.getRs2PreparedString("Enter your username (V password)3");
    public static JagexString aJagexString_324 = JagexString.getRs2PreparedString("sl_stars");
    public static JagexString aJagexString_328 = JagexString.getRs2PreparedString("Ihre Freunde)2Liste ist voll(Q Mitglieder k-Onnen 200 Freunde hinzuf-Ugen)1 freie Spieler nur 100)3");
    public static JagexString aJagexString_346 = JagexString.getRs2PreparedString("Malformed login packet)3");
    public static JagexString aJagexString_361 = JagexString.getRs2PreparedString("sl_arrows");
    public static JagexString aJagexString_363 = JagexString.getRs2PreparedString("Service unavailable)3");
    public static JagexString aJagexString_370 = JagexString.getRs2PreparedString("Error loading your profile)3");
    public static JagexString aJagexString_373 = JagexString.getRs2PreparedString("Bitte entfernen Sie ");
    public static JagexString aJagexString_386 = JagexString.getRs2PreparedString("welle2:");
    public static JagexString aJagexString_2469 = JagexString.getRs2PreparedString("me");
    public static JagexString aJagexString_2474 = JagexString.getRs2PreparedString("flash1:");
    public static JagexString aJagexString_2475 = JagexString.getRs2PreparedString("Update)2Liste geladen)3");
    public static JagexString aJagexString_2477 = JagexString.getRs2PreparedString("Bitte laden Sie die Seite neu)3");
    public static JagexString aJagexString_2479 = JagexString.getRs2PreparedString("flash1:");
    public static JagexString aJagexString_390 = JagexString.getRs2PreparedString("Musik)2Engine vorbereitet)3");
    public static JagexString aJagexString_393 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_396 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_397 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_398 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_400 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_402 = JagexString.getRs2PreparedString("(Udns");
    public static JagexString aJagexString_403 = JagexString.getRs2PreparedString("white:");
    public static JagexString aJagexString_407 = JagexString.getRs2PreparedString("white:");
    public static JagexString aJagexString_411 = JagexString.getRs2PreparedString("Please try using a different world)3");
    public static JagexString aJagexString_413 = JagexString.getRs2PreparedString("Sie k-Onnen sich selbst nicht auf Ihre Freunde)2Liste setzen(Q");
    public static JagexString aJagexString_432 = JagexString.getRs2PreparedString("Loading textures )2 ");
    public static JagexString aJagexString_434 = JagexString.getRs2PreparedString("Walk here");
    public static JagexString aJagexString_445 = JagexString.getRs2PreparedString("<col=00ff80>");
    public static JagexString aJagexString_451 = JagexString.getRs2PreparedString("rect_debug=");
    public static JagexString aJagexString_2936 = JagexString.getRs2PreparedString("Cabbage");
    public static JagexString aJagexString_2101 = JagexString.getRs2PreparedString(":");
    public static JagexString aJagexString_2115 = JagexString.getRs2PreparedString(": ");
    public static JagexString aJagexString_368 = JagexString.getRs2PreparedString("l");
    public static JagexString aJagexString_464 = JagexString.getRs2PreparedString("Wir vermuten)1 dass Ihr Konto gestohlen wurde");
    public static JagexString aJagexString_470 = JagexString.getRs2PreparedString("Try again in 60 secs)3)3)3");
    public static JagexString aJagexString_472 = JagexString.getRs2PreparedString("k");
    public static JagexString aJagexString_474 = (JagexString.getRs2PreparedString("Benutzen Sie die (WPasswort -=ndern(W Option"));
    public static JagexString aJagexString_478 = JagexString.getRs2PreparedString(":tradereq:");
    public static JagexString aJagexString_484 = JagexString.getRs2PreparedString("<)4col> x");
    public static JagexString aJagexString_495 = (JagexString.getRs2PreparedString("Verbindung konnte nicht hergestellt werden)3"));
    public static JagexString aJagexString_517 = JagexString.getRs2PreparedString("<col=ffffff> )4 ");
    public static JagexString aJagexString_2514 = JagexString.getRs2PreparedString("Loaded wordpack");
    public static JagexString aJagexString_2515 = JagexString.getRs2PreparedString("Bitte geben Sie Ihr Passwort ein)3");
    public static JagexString aJagexString_2518 = JagexString.getRs2PreparedString(":chalreq:");
    public static JagexString aJagexString_2528 = JagexString.getRs2PreparedString("mapscene");
    public static JagexString aJagexString_81 = JagexString.getRs2PreparedString("Clientscript error in: ");
    public static JagexString aJagexString_85 = JagexString.getRs2PreparedString("_");
    public static JagexString aJagexString_92 = JagexString.getRs2PreparedString("titlebox");
    public static JagexString aJagexString_93 = JagexString.getRs2PreparedString("No response from server)3");
    public static JagexString aJagexString_558 = JagexString.getRs2PreparedString("0(U");
    public static JagexString aJagexString_560 = JagexString.getRs2PreparedString("AUS");
    public static JagexString aJagexString_563 = JagexString.getRs2PreparedString("Choose Option");
    public static JagexString aJagexString_564 = JagexString.getRs2PreparedString("Drop");
    public static JagexString aJagexString_565 = JagexString.getRs2PreparedString(":assistreq:");
    public static JagexString aJagexString_551 = JagexString.getRs2PreparedString("Hidden)2");
    public static JagexString aJagexString_581 = JagexString.getRs2PreparedString(" is already on your friend list");
    public static JagexString aJagexString_586 = JagexString.getRs2PreparedString("Select");
    public static JagexString aJagexString_594 = JagexString.getRs2PreparedString("Bitte versuchen Sie)1");
    public static JagexString aJagexString_595 = JagexString.getRs2PreparedString("Angreifen");
    public static JagexString aJagexString_596 = (JagexString.getRs2PreparedString("Spieler)3 Bitte w-=hlen Sie eine andere Welt)3"));
    public static JagexString aJagexString_622 = JagexString.getRs2PreparedString("::clientdrop");
    public static JagexString aJagexString_623 = JagexString.getRs2PreparedString("Bitte versuchen Sie es in ");
    public static JagexString aJagexString_624 = JagexString.getRs2PreparedString("Your friend list is full)3 Max of 100 for free users)1 and 200 for members");
    public static JagexString aJagexString_629 = JagexString.getRs2PreparedString("Members only world");
    public static JagexString aJagexString_638 = JagexString.getRs2PreparedString("Hidden");
    public static JagexString aJagexString_651 = JagexString.getRs2PreparedString("Invalid loginserver requested)3");
    public static JagexString aJagexString_652 = JagexString.getRs2PreparedString("(Y");
    public static JagexString aJagexString_653 = JagexString.getRs2PreparedString(" zuerst von Ihrer Freunde)2Liste(Q");
    public static JagexString aJagexString_659 = JagexString.getRs2PreparedString("::fpsoff");
    public static JagexString aJagexString_662 = JagexString.getRs2PreparedString("Loading title screen )2 ");
    public static JagexString aJagexString_665 = JagexString.getRs2PreparedString("Examine");
    public static JagexString aJagexString_675 = JagexString.getRs2PreparedString("Create a free account");
    public static JagexString aJagexString_678 = JagexString.getRs2PreparedString("sl_back");
    public static JagexString aJagexString_679 = JagexString.getRs2PreparedString("Bad session id)3");
    public static JagexString aJagexString_681 = JagexString.getRs2PreparedString("M");
    public static JagexString aJagexString_684 = JagexString.getRs2PreparedString("(U(Y");
    public static JagexString aJagexString_685 = JagexString.getRs2PreparedString("Diese Welt ist voll)3");
    public static JagexString aJagexString_688 = JagexString.getRs2PreparedString("Spiel)2Engine wird gestartet)3)3)3");
    public static JagexString aJagexString_692 = JagexString.getRs2PreparedString("Bad session id)3");
    public static JagexString aJagexString_695 = JagexString.getRs2PreparedString("blaugr-Un:");
    public static JagexString aJagexString_700 = JagexString.getRs2PreparedString("Lade Benutzeroberfl-=che )2 ");
    public static JagexString aJagexString_701 = JagexString.getRs2PreparedString("Passwort: ");
    public static JagexString aJagexString_1753 = JagexString.getRs2PreparedString("Bitte versuchen Sie es erneut)3");
    public static JagexString aJagexString_1759 = JagexString.getRs2PreparedString(")3runescape)3com");
    public static JagexString aJagexString_1762 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1764 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1766 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1768 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1769 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1771 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_1767 = JagexString.getRs2PreparedString("");
    public static JagexString aJagexString_728 = JagexString.getRs2PreparedString("You are standing in a members)2only area)3");
    public static JagexString aJagexString_735 = JagexString.getRs2PreparedString("null");
    public static JagexString aJagexString_741 = JagexString.getRs2PreparedString("Zu viele Anmelde)2Versuche von Ihrer Adresse");
    public static JagexString aJagexString_753 = JagexString.getRs2PreparedString("Sorry invited players only)3");
    public static JagexString aJagexString_762 = JagexString.getRs2PreparedString("hitmarks");
    public static JagexString aJagexString_765 = JagexString.getRs2PreparedString("Please subscribe)1 or use a different world)3");
    public static JagexString aJagexString_769 = JagexString.getRs2PreparedString("Standort");
    public static JagexString aJagexString_772 = JagexString.getRs2PreparedString("scrollbar");
    public static JagexString aJagexString_788 = JagexString.getRs2PreparedString("We suspect someone knows your password)3");
    public static JagexString aJagexString_791 = JagexString.getRs2PreparedString(" )2>");
    public static JagexString aJagexString_797 = JagexString.getRs2PreparedString("This computers address has been blocked");
    public static JagexString aJagexString_804 = JagexString.getRs2PreparedString("null");
    public static JagexString aJagexString_835 = JagexString.getRs2PreparedString("oder benutzen Sie eine andere Welt)3");
    public static JagexString aJagexString_836 = JagexString.getRs2PreparedString("cyan:");
    public static JagexString aJagexString_838 = JagexString.getRs2PreparedString(" <col=ffffff>");
    public static JagexString aJagexString_839 = JagexString.getRs2PreparedString("cyan:");
    public static JagexString aJagexString_840 = JagexString.getRs2PreparedString("huffman");
    public static JagexString aJagexString_842 = JagexString.getRs2PreparedString(" )2> <col=ff9040>");
    public static JagexString aJagexString_843 = JagexString.getRs2PreparedString("Diese Betatest)2Welt ist nur f-Ur eingeladene");
    public static JagexString aJagexString_846 = JagexString.getRs2PreparedString(")2");
    public static JagexString aJagexString_850 = JagexString.getRs2PreparedString("Benutzen Sie bitte eine andere Welt)3");
    public static JagexString aJagexString_857 = JagexString.getRs2PreparedString(")1p");
    public static JagexString aJagexString_864  = JagexString.getRs2PreparedString("Loaded textures");
    public static JagexString aJagexString_867  = JagexString.getRs2PreparedString("as it was used to break our rules)3");
    public static JagexString aJagexString_889 = JagexString.getRs2PreparedString("Bitte wenden Sie sich an den Kundendienst)3");
    public static JagexString aJagexString_905  = JagexString.getRs2PreparedString("Login server offline)3");
    public static JagexString aJagexString_918 = JagexString.getRs2PreparedString("Mem:");
    public static JagexString aJagexString_921 = JagexString.getRs2PreparedString("Schlie-8en");
    public static JagexString aJagexString_922 = JagexString.getRs2PreparedString(" <col=ffff00>");
    public static JagexString aJagexString_924 = JagexString.getRs2PreparedString("Lade Sprites )2 ");
    public static JagexString aJagexString_925 = JagexString.getRs2PreparedString("<col=ff7000>");
}
